alter table finance_reparation_file drop constraint FK_FINANCE_REPARATION_FILE_ON_PARTITION ;
alter table finance_reparation_files_structure drop constraint FK_FINANCE_REPARATION_FILES_STRUCTURE_ON_PARTITION ;
