alter table finance_reparation_file drop constraint FK_FINANCE_REPARATION_FILE_ON_DOCUMENT_TYPE ;
alter table finance_reparation_files_structure drop constraint FK_FINANCE_REPARATION_FILES_STRUCTURE_ON_DOCUMENT_TYPE ;
