alter table FINANCE_ADDRESSING_DETAIL add constraint FK_FINANCE_ADDRESSING_DETAIL_ON_PROC_ROLE foreign key (PROC_ROLE_ID) references BPM_PROC_ROLE(ID);
alter table FINANCE_ADDRESSING_DETAIL add constraint FK_FINANCE_ADDRESSING_DETAIL_ON_USER foreign key (USER_ID) references SEC_USER(ID);
alter table FINANCE_ADDRESSING_DETAIL add constraint FK_FINANCE_ADDRESSING_DETAIL_ON_ADDRESSING foreign key (ADDRESSING_ID) references FINANCE_ADDRESSING(ID);
create index IDX_FINANCE_ADDRESSING_DETAIL_ON_PROC_ROLE on FINANCE_ADDRESSING_DETAIL (PROC_ROLE_ID);
create index IDX_FINANCE_ADDRESSING_DETAIL_ON_USER on FINANCE_ADDRESSING_DETAIL (USER_ID);
create index IDX_FINANCE_ADDRESSING_DETAIL_ON_ADDRESSING on FINANCE_ADDRESSING_DETAIL (ADDRESSING_ID);
