alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_STATUS foreign key (STATUS_ID) references FINANCE_PROC_STATUS(ID);
create index IDX_FINANCE_PAYMENT_CLAIM_ON_STATUS on FINANCE_PAYMENT_CLAIM (STATUS_ID);
