-- begin FINANCE_PAYMENT_REGISTER
alter table FINANCE_PAYMENT_REGISTER add constraint FK_FINANCE_PAYMENT_REGISTER_ON_BUSINESS foreign key (BUSINESS_ID) references FINANCE_BUSINESS(ID)^
alter table FINANCE_PAYMENT_REGISTER add constraint FK_FINANCE_PAYMENT_REGISTER_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_ON_BUSINESS on FINANCE_PAYMENT_REGISTER (BUSINESS_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_ON_AUTHOR on FINANCE_PAYMENT_REGISTER (AUTHOR_ID)^
-- end FINANCE_PAYMENT_REGISTER
-- begin FINANCE_PAYMENT_REGISTER_DETAIL
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_COMPANY foreign key (COMPANY_ID) references FINANCE_COMPANY(ID)^
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_CLIENT foreign key (CLIENT_ID) references FINANCE_CLIENT(ID)^
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_CASH_FLOW_ITEM foreign key (CASH_FLOW_ITEM_ID) references FINANCE_CASH_FLOW_ITEM(ID)^
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_TYPE foreign key (PAYMENT_TYPE_ID) references FINANCE_PAYMENT_TYPE(ID)^
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_CLAIM foreign key (PAYMENT_CLAIM_ID) references FINANCE_PAYMENT_CLAIM(ID)^
alter table FINANCE_PAYMENT_REGISTER_DETAIL add constraint FK_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_REGISTER foreign key (PAYMENT_REGISTER_ID) references FINANCE_PAYMENT_REGISTER(ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_COMPANY on FINANCE_PAYMENT_REGISTER_DETAIL (COMPANY_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_CLIENT on FINANCE_PAYMENT_REGISTER_DETAIL (CLIENT_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_CASH_FLOW_ITEM on FINANCE_PAYMENT_REGISTER_DETAIL (CASH_FLOW_ITEM_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_TYPE on FINANCE_PAYMENT_REGISTER_DETAIL (PAYMENT_TYPE_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_CLAIM on FINANCE_PAYMENT_REGISTER_DETAIL (PAYMENT_CLAIM_ID)^
create index IDX_FINANCE_PAYMENT_REGISTER_DETAIL_ON_PAYMENT_REGISTER on FINANCE_PAYMENT_REGISTER_DETAIL (PAYMENT_REGISTER_ID)^
-- end FINANCE_PAYMENT_REGISTER_DETAIL
-- begin FINANCE_PAYMENT_CLAIM
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_BUSINESS foreign key (BUSINESS_ID) references FINANCE_BUSINESS(ID)^
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_COMPANY foreign key (COMPANY_ID) references FINANCE_COMPANY(ID)^
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_CLIENT foreign key (CLIENT_ID) references FINANCE_CLIENT(ID)^
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_CASH_FLOW_ITEM foreign key (CASH_FLOW_ITEM_ID) references FINANCE_CASH_FLOW_ITEM(ID)^
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_PAYMENT_TYPE foreign key (PAYMENT_TYPE_ID) references FINANCE_PAYMENT_TYPE(ID)^
alter table FINANCE_PAYMENT_CLAIM add constraint FK_FINANCE_PAYMENT_CLAIM_ON_AUTHOR foreign key (AUTHOR_ID) references SEC_USER(ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_BUSINESS on FINANCE_PAYMENT_CLAIM (BUSINESS_ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_COMPANY on FINANCE_PAYMENT_CLAIM (COMPANY_ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_CLIENT on FINANCE_PAYMENT_CLAIM (CLIENT_ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_CASH_FLOW_ITEM on FINANCE_PAYMENT_CLAIM (CASH_FLOW_ITEM_ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_PAYMENT_TYPE on FINANCE_PAYMENT_CLAIM (PAYMENT_TYPE_ID)^
create index IDX_FINANCE_PAYMENT_CLAIM_ON_AUTHOR on FINANCE_PAYMENT_CLAIM (AUTHOR_ID)^
-- end FINANCE_PAYMENT_CLAIM
-- begin FINANCE_COMPANY
alter table FINANCE_COMPANY add constraint FK_FINANCE_COMPANY_ON_BUSINESS foreign key (BUSINESS_ID) references FINANCE_BUSINESS(ID)^
create index IDX_FINANCE_COMPANY_ON_BUSINESS on FINANCE_COMPANY (BUSINESS_ID)^
-- end FINANCE_COMPANY
-- begin FINANCE_USER_PROPERTY
alter table FINANCE_USER_PROPERTY add constraint FK_FINANCE_USER_PROPERTY_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table FINANCE_USER_PROPERTY add constraint FK_FINANCE_USER_PROPERTY_ON_BUSINESS foreign key (BUSINESS_ID) references FINANCE_BUSINESS(ID)^
alter table FINANCE_USER_PROPERTY add constraint FK_FINANCE_USER_PROPERTY_ON_COMPANY foreign key (COMPANY_ID) references FINANCE_COMPANY(ID)^
create index IDX_FINANCE_USER_PROPERTY_ON_USER on FINANCE_USER_PROPERTY (USER_ID)^
create index IDX_FINANCE_USER_PROPERTY_ON_BUSINESS on FINANCE_USER_PROPERTY (BUSINESS_ID)^
create index IDX_FINANCE_USER_PROPERTY_ON_COMPANY on FINANCE_USER_PROPERTY (COMPANY_ID)^
-- end FINANCE_USER_PROPERTY
-- begin FINANCE_BUSINESS
alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_FIN_CONTROLER foreign key (FIN_CONTROLER_ID) references SEC_USER(ID)^
alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_FIN_DIRECTOR foreign key (FIN_DIRECTOR_ID) references SEC_USER(ID)^
alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_GEN_DIRECTOR foreign key (GEN_DIRECTOR_ID) references SEC_USER(ID)^
alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_FIN_CONTROLER_SH foreign key (FIN_CONTROLER_SH_ID) references SEC_USER(ID)^
alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_GEN_DIRECTOR_SH foreign key (GEN_DIRECTOR_SH_ID) references SEC_USER(ID)^
create index IDX_FINANCE_BUSINESS_ON_FIN_CONTROLER on FINANCE_BUSINESS (FIN_CONTROLER_ID)^
create index IDX_FINANCE_BUSINESS_ON_FIN_DIRECTOR on FINANCE_BUSINESS (FIN_DIRECTOR_ID)^
create index IDX_FINANCE_BUSINESS_ON_GEN_DIRECTOR on FINANCE_BUSINESS (GEN_DIRECTOR_ID)^
create index IDX_FINANCE_BUSINESS_ON_FIN_CONTROLER_SH on FINANCE_BUSINESS (FIN_CONTROLER_SH_ID)^
create index IDX_FINANCE_BUSINESS_ON_GEN_DIRECTOR_SH on FINANCE_BUSINESS (GEN_DIRECTOR_SH_ID)^
-- end FINANCE_BUSINESS
