alter table FINANCE_ACCOUNT_REMAINS add constraint FK_FINANCE_ACCOUNT_REMAINS_ON_ACCOUNT foreign key (ACCOUNT_ID) references FINANCE_ACCOUNT(ID);
create index IDX_FINANCE_ACCOUNT_REMAINS_ON_ACCOUNT on FINANCE_ACCOUNT_REMAINS (ACCOUNT_ID);
