alter table FINANCE_ACCOUNT_REMAINS add constraint FK_FINANCE_ACCOUNT_REMAINS_ON_COMPANY foreign key (COMPANY_ID) references FINANCE_COMPANY(ID);
create index IDX_FINANCE_ACCOUNT_REMAINS_ON_COMPANY on FINANCE_ACCOUNT_REMAINS (COMPANY_ID);
