alter table FINANCE_ACCOUNT_REMAINS add constraint FK_FINANCE_ACCOUNT_REMAINS_ON_BUSSINES foreign key (BUSSINES_ID) references FINANCE_BUSINESS(ID);
create index IDX_FINANCE_ACCOUNT_REMAINS_ON_BUSSINES on FINANCE_ACCOUNT_REMAINS (BUSSINES_ID);
