alter table FINANCE_BUSINESS add constraint FK_FINANCE_BUSINESS_ON_PARENT foreign key (PARENT_ID) references FINANCE_BUSINESS(ID);
create index IDX_FINANCE_BUSINESS_ON_PARENT on FINANCE_BUSINESS (PARENT_ID);
