alter table FINANCE_BANK add constraint FK_FINANCE_BANK_ON_PARENT_BANK foreign key (PARENT_BANK_ID) references FINANCE_BANK(ID);
create index IDX_FINANCE_BANK_ON_PARENT_BANK on FINANCE_BANK (PARENT_BANK_ID);
