export enum ClaimStatusEnum {
  NEW = "NEW",
  IN_APPROVE = "IN_APPROVE",
  APPROVED_FIN_CONTROLER = "APPROVED_FIN_CONTROLER",
  REJECTED_FIN_CONTROLER = "REJECTED_FIN_CONTROLER",
  APPROVED_FIN_DIR = "APPROVED_FIN_DIR",
  REJECTED_FIN_DIR = "REJECTED_FIN_DIR"
}

export enum ClientTypeEnum {
  JUR_OSOBA = "JUR_OSOBA",
  FIZ_OSOBA = "FIZ_OSOBA"
}

export enum PaymentRegisterDetailStatusEnum {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  TERMINATED = "TERMINATED"
}
